version: "3.3"
services:
  api:
    build: ./api
  bert-server:
    build: ./bert-server
    volumes:
      - ./bert-server/bert-models:/app/bert-models
  frontend:
    build: ./frontend
    ports:
      - "5811:3000"